# Makefile automatically generated by ghdl
# Version: GHDL 1.0.0 (Ubuntu 1.0.0+dfsg-6) [Dunoon edition] - GCC back-end code generator
# Command used to generate this makefile:
# /usr/bin/ghdl-gcc --gen-makefile --ieee=synopsys -fexplicit --workdir=WORK testbench

GHDL=/usr/bin/ghdl-gcc
GHDLFLAGS= --ieee=synopsys -fexplicit --workdir=WORK

# Default target
all: testbench

# Elaboration target
testbench: /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164-body.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std-body.o WORK/testbench_AOC2_SoC.o WORK/AOC2_SoC_2026.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_arith.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o WORK/IO_MD_subsystem_P2_26.o WORK/INCOMPLETE_Mips_segmentado_IRQ_2026.o WORK/MC_datos_CB_2026.o WORK/MD_cont_2026.o WORK/MD_scratch_2026.o WORK/arbitro.o WORK/counter.o WORK/IO_master_2026.o WORK/REGISTER.o WORK/Via_2026_CB.o WORK/FIFO_reg.o WORK/Completar_UC_MC_2026.o WORK/memoriaRAM_128_32_2026_bucle_lectura.o WORK/memoriaRAM_64_32_enable.o WORK/adder32.o WORK/memoriaRAM_I_test.bucle_lectura.P2.o WORK/Banco_ID.o WORK/BReg.o WORK/Ext_signo.o WORK/bits_shifter.o WORK/INCOMPLETE_UC_Mips_2026.o WORK/INCOMPLETE_UD_2026.o WORK/Banco_EX.o WORK/INCOMPLETE_UA_2026.o WORK/mux4_1.o WORK/mux2_1.o WORK/ALU_2026.o WORK/mux2_5bits.o WORK/Banco_MEM.o WORK/Exception_manager.o WORK/Banco_WB.o
	$(GHDL) -e $(GHDLFLAGS) $@

# Run target
run: testbench
	$(GHDL) -r testbench $(GHDLRUNFLAGS)

# Targets to analyze files
/usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o: /usr/lib/ghdl/gcc/vhdl/ieee/v93/../../src/ieee/v93/std_logic_1164.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164-body.o: /usr/lib/ghdl/gcc/vhdl/ieee/v93/../../src/ieee/v93/std_logic_1164-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o: /usr/lib/ghdl/gcc/vhdl/ieee/v93/../../src/ieee/v93/numeric_std.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std-body.o: /usr/lib/ghdl/gcc/vhdl/ieee/v93/../../src/ieee/v93/numeric_std-body.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
WORK/testbench_AOC2_SoC.o: testbench_AOC2_SoC.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/AOC2_SoC_2026.o: AOC2_SoC_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
/usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_arith.o: /usr/lib/ghdl/gcc/vhdl/ieee/v93/../../src/synopsys/std_logic_arith.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
/usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o: /usr/lib/ghdl/gcc/vhdl/ieee/v93/../../src/synopsys/std_logic_unsigned.vhdl
	@echo "This file was not locally built ($<)"
	exit 1
WORK/IO_MD_subsystem_P2_26.o: IO_MD_subsystem_P2_26.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/INCOMPLETE_Mips_segmentado_IRQ_2026.o: INCOMPLETE_Mips_segmentado_IRQ_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/MC_datos_CB_2026.o: MC_datos_CB_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/MD_cont_2026.o: MD_cont_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/MD_scratch_2026.o: MD_scratch_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/arbitro.o: arbitro.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/counter.o: counter.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/IO_master_2026.o: IO_master_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/REGISTER.o: REGISTER.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/Via_2026_CB.o: Via_2026_CB.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/FIFO_reg.o: FIFO_reg.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/Completar_UC_MC_2026.o: Completar_UC_MC_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/memoriaRAM_128_32_2026_bucle_lectura.o: memoriaRAM_128_32_2026_bucle_lectura.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/memoriaRAM_64_32_enable.o: memoriaRAM_64_32_enable.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/adder32.o: adder32.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/memoriaRAM_I_test.bucle_lectura.P2.o: memoriaRAM_I_test.bucle_lectura.P2.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/Banco_ID.o: Banco_ID.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/BReg.o: BReg.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/Ext_signo.o: Ext_signo.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/bits_shifter.o: bits_shifter.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/INCOMPLETE_UC_Mips_2026.o: INCOMPLETE_UC_Mips_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/INCOMPLETE_UD_2026.o: INCOMPLETE_UD_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/Banco_EX.o: Banco_EX.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/INCOMPLETE_UA_2026.o: INCOMPLETE_UA_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/mux4_1.o: mux4_1.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/mux2_1.o: mux2_1.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/ALU_2026.o: ALU_2026.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/mux2_5bits.o: mux2_5bits.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/Banco_MEM.o: Banco_MEM.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/Exception_manager.o: Exception_manager.vhd
	$(GHDL) -a $(GHDLFLAGS) $<
WORK/Banco_WB.o: Banco_WB.vhd
	$(GHDL) -a $(GHDLFLAGS) $<

# Files dependences
/usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o: 
/usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164-body.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
/usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
/usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std-body.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
WORK/testbench_AOC2_SoC.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164-body.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std-body.o
WORK/AOC2_SoC_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
/usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_arith.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
/usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_arith.o
WORK/IO_MD_subsystem_P2_26.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o
WORK/INCOMPLETE_Mips_segmentado_IRQ_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/MC_datos_CB_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
WORK/MD_cont_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_arith.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o
WORK/MD_scratch_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_arith.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o
WORK/arbitro.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/counter.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_arith.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
WORK/IO_master_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/REGISTER.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
WORK/Via_2026_CB.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
WORK/FIFO_reg.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o
WORK/Completar_UC_MC_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/memoriaRAM_128_32_2026_bucle_lectura.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
WORK/memoriaRAM_64_32_enable.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
WORK/adder32.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_arith.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
WORK/memoriaRAM_I_test.bucle_lectura.P2.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o
WORK/Banco_ID.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/BReg.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o
WORK/Ext_signo.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/bits_shifter.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/INCOMPLETE_UC_Mips_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/INCOMPLETE_UD_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/Banco_EX.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/INCOMPLETE_UA_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/mux4_1.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/mux2_1.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/ALU_2026.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_unsigned.o /usr/lib/ghdl/gcc/vhdl/ieee/v93/numeric_std.o
WORK/mux2_5bits.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/Banco_MEM.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/Exception_manager.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
WORK/Banco_WB.o:  /usr/lib/ghdl/gcc/vhdl/ieee/v93/std_logic_1164.o
